Converted project to requirejs. The twitter bootstrap stylesheets and js, as well as dependent jquery and the ability to bring in both css and coffeescript includes via require are included. grunt-cli: The grunt command line interface. (v0.1.11)
Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started will switch out paths in both index.html and requirejs-config.sjs
to be the data-alt-path if needed.